# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Crate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='InterestGroup',
            fields=[
                ('interest_id', models.IntegerField(primary_key=True, serialize=False)),
                ('interest_group_name', models.CharField(max_length=30)),
                ('subscription_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('have', models.ManyToManyField(to='Crate.Item')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcategory_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hierarchy.Category')),
            ],
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='subcategory_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hierarchy.SubCategory'),
        ),
    ]
