# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 01:08
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='InterestGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_group_name', models.CharField(max_length=30)),
                ('subscription_cost', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('item_description', models.CharField(max_length=500)),
                ('item_quantity', models.IntegerField(default=0)),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=6)),
                ('contained_in', models.ManyToManyField(to='Crate.Box')),
                ('sold_by', models.ManyToManyField(through='inventory.SellingOrder', to='inventory.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SellingCycle',
            fields=[
                ('cycle_date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcategory_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crate.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(default=0)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crate.Item')),
                ('selling_cycle',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crate.SellingCycle')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='sold_in',
            field=models.ManyToManyField(to='Crate.SellingCycle'),
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='have',
            field=models.ManyToManyField(to='Crate.Item'),
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='subcategory_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crate.SubCategory'),
        ),
        migrations.AddField(
            model_name='box',
            name='sold_during',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crate.SellingCycle'),
        ),
        migrations.AddField(
            model_name='box',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crate.InterestGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='votes',
            unique_together=set([('item_id', 'selling_cycle')]),
        ),
    ]
