# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarchy', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('box_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SellingCycle',
            fields=[
                ('cycle_date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='sold_during',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crate.SellingCycle'),
        ),
        migrations.AddField(
            model_name='box',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hierarchy.InterestGroup'),
        ),
    ]
