# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('box_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('item_description', models.CharField(max_length=500)),
                ('item_quantity', models.IntegerField(default=0)),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=6)),
                ('contained_in', models.ManyToManyField(to='Crate.Box')),
                ('sold_by', models.ManyToManyField(through='inventory.SellingOrder', to='inventory.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SellingCycle',
            fields=[
                ('cycle_date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='sold_in',
            field=models.ManyToManyField(to='Crate.SellingCycle'),
        ),
        migrations.AddField(
            model_name='box',
            name='sold_during',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crate.SellingCycle'),
        ),
    ]
