# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 04:08
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Crate', '0001_initial'),
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hierarchy.InterestGroup'),
        ),
    ]
