# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('cc_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('csv', models.CharField(max_length=4)),
                ('expiration_date', models.CharField(max_length=6)),
                ('billing_address', models.CharField(max_length=100)),
            ],
        ),
    ]
